"""Pure retrieval engines and their versioned internal contracts."""

from .baseline import (
    BASELINE_DOCUMENT_FORMAT_VERSION,
    BASELINE_TOKENIZER_VERSION,
    BaselineV1Retriever,
    baseline_ranking_document,
    bm25_scores,
    enumerate_file_candidates,
    frozen_tokens,
    reciprocal_rank_fusion,
)
from .factory import (
    BASELINE_RETRIEVAL_ENGINE,
    DEFAULT_RETRIEVAL_ENGINE,
    BaselineV1Invocation,
    UnknownRetrievalEngineError,
    create_retrieval_engine,
    invoke_retrieval,
    retrieve_reference_evidence,
    validate_retrieval_engine_name,
)
from .legacy import LegacyRetriever
from .processing import (
    BASELINE_DOCUMENT_PROCESSING_SCHEMA_VERSION,
    BASELINE_PROCESSING_OUTCOME_SCHEMA_VERSION,
    BaselineProcessingOutcome,
    BaselineProcessingStatus,
    ProcessingRunIdentityError,
    baseline_document_processing_outcome,
    derive_baseline_persistence_idempotency_key,
    new_processing_run_key,
    processing_run_trace_id,
    validate_baseline_group_id,
    validate_processing_run_key,
)
from .types import (
    DenseEmbeddingProvider,
    FileCandidate,
    RetrievalCandidate,
    RetrievalError,
    RetrievalEvidence,
    RetrievalQueryOrigin,
    RetrievalQueryProvenance,
    RetrievalRequest,
    RetrievalResult,
    RetrievalStatus,
    retrieval_query_provenance,
)

__all__ = [
    "BASELINE_DOCUMENT_FORMAT_VERSION",
    "BASELINE_DOCUMENT_PROCESSING_SCHEMA_VERSION",
    "BASELINE_PROCESSING_OUTCOME_SCHEMA_VERSION",
    "BASELINE_RETRIEVAL_ENGINE",
    "BASELINE_TOKENIZER_VERSION",
    "DEFAULT_RETRIEVAL_ENGINE",
    "BaselineProcessingOutcome",
    "BaselineProcessingStatus",
    "BaselineV1Invocation",
    "BaselineV1Retriever",
    "DenseEmbeddingProvider",
    "FileCandidate",
    "LegacyRetriever",
    "ProcessingRunIdentityError",
    "RetrievalCandidate",
    "RetrievalError",
    "RetrievalEvidence",
    "RetrievalQueryOrigin",
    "RetrievalQueryProvenance",
    "RetrievalRequest",
    "RetrievalResult",
    "RetrievalStatus",
    "UnknownRetrievalEngineError",
    "baseline_document_processing_outcome",
    "baseline_ranking_document",
    "bm25_scores",
    "create_retrieval_engine",
    "derive_baseline_persistence_idempotency_key",
    "enumerate_file_candidates",
    "frozen_tokens",
    "invoke_retrieval",
    "new_processing_run_key",
    "processing_run_trace_id",
    "reciprocal_rank_fusion",
    "retrieval_query_provenance",
    "retrieve_reference_evidence",
    "validate_baseline_group_id",
    "validate_processing_run_key",
    "validate_retrieval_engine_name",
]
